nelmio_api_doc:
    documentation:
        info:
            title: "Medisys API"
            description: "API REST pour la gestion des patients (Symfony 7)"
            version: "1.0.0"
    areas:
        default:
            path_patterns: [^/api]
